version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: debug1
      POSTGRES_PASSWORD: debug1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgadmin:  
    container_name: pgadmin4_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: root  
    ports:  
      - "5050:80"